let dados = [
    {
        produto: 'Fone sem fio',
        categoria:'Celular', 
        descricao:'Fone De Ouvido Sem Fio bluetooth 5.0 Display Headset Compatível com todos os aparelhos',
        valor: 'R$ 34,90',
        url:'../img/fone.jpg',
    },
    {
        produto: 'Carregador',
        categoria:'Celular',
        descricao:'Kit de Carregador Turbo Android 30W 4.0 Entrada Tipo-C + Cabo USB - Tipo C 1m (Branco)',
        valor: 'R$ 44,90',
        url:'../img/carregador.jpg',
    },
    {
        produto: 'Película vidro',
        categoria:'Celular',
        descricao:'Película de Vidro Temperado iPhone XR Bordas Pretas, Cobertura Total, varios modelos',
        valor: 'R$ 19,90',
        url:'../img/pelicula.jpg',
    },
    {
        produto: 'Controle TV',
        categoria:'TV',
        descricao:'Controles de todas as marcas: LG, Samsung, Philips, Philco, AOC, Sony, Buster, CCE...',
        valor: 'R$ 19,90',
        url:'../img/controle.jpg',
    },
    {
        produto: 'Antena Interna',
        categoria:'TV',
        descricao:'Antena de TV Interna UHF/HDTV AI 2025 Preto Intelbras com Cabo de 2,5 metros',
        valor: 'R$ 39,90',
        url:'../img/antena.jpg',
    },
    {
        produto: 'Pen drive',
        categoria:'Computador',
        descricao:'Sandisk Pen drive USB Cruzer Blade, 64 GB, preto/vermelho à prova de quedas, leitura rápida',
        valor: 'R$ 49,90',
        url:'../img/pendrive.jpg',
    },
    {
        produto: 'SSD',
        categoria:'Computador',
        descricao:'SanDisk SSD interno de 1 TB - SATA III 6 Gb/s, 7 mm, até 535 MB/s - SDSSDA-1T00-G27',
        valor: 'R$ 389,90',
        url:'../img/ssd.jpg',
    },
    {
        produto: 'Headset',
        categoria:'Computador',
        descricao:'Headset Gamer Mancer Twilight, Rainbow, Drivers 50mm, Preto, MCR-TLT-RGB02',
        valor: 'R$ 129,90',
        url:'../img/headset.jpg',
    },
    {
        produto: 'Câmera',
        categoria:'Eletrônicos',
        descricao:'Camera Dome Wifi HD 360 Visao Noturna Panoramica Segurança Sem Fio, fácil configuração',
        valor: 'R$ 169,90',
        url:'../img/camera.jpg',
    },
    {
        produto: 'Mini caixa de som',
        categoria:'Eletrônicos',
        descricao:'Mini Caixa de Som Bluetooth Metal Amplificada Mini Speaker 3w - Vermelho, cinza',
        valor: 'R$ 49,90',
        url:'../img/mini.jpg',
    },
    {
        produto: 'Roteador',
        categoria:'Internet',
        descricao:'ROTEADOR WIRELESS 300 MBPS  2 ANTENAS TL-WR840N-W 2 Antenas externas WPS',
        valor: 'R$ 149,90',
        url:'../img/roteador.jpg',
    },
    {
        produto: 'Bateria',
        categoria:'Bateria',
        descricao:'Bateria De Lítio 3V CR2032 Cartela Com 5 Unidades Para Relógios Calculadoras Alarmes',
        valor: 'R$ 30,00',
        url:'../img/bateria.jpg',
    },
  
]